some preparatory work before introducing a package.
kierun/character-background-template pull request #1
Opened 2023-03-26 01:10 UTC by stevecooperorg

Three commits here, each doing a little bit, and each one commented.

I'm in the process of trying to extract out a style --- so you can do `\usepackage[modern]{rpg}` or `\usepackage[fantasy]{rpg}` --- but in doing so I needed to get a few things off.

Really this is so that I've actually raised a first PR into the repo...

2023-03-26 18:22 UTC, kierun commented
@stevecooperorg Thank you for the PR. It is much appreciated. :heart: 

I have been using [git conventional commit](https://www.conventionalcommits.org/en/v1.0.0/), which could be overkill for this. ¯\\\_(ツ)\_/¯

2023-03-27 15:33 UTC, kierun requested changes

2023-03-27 15:33 UTC, kierun commented on Makefile
> +	$(LATEXMK) -xelatex -interaction=nonstopmode $(PREVIEW) $*
`-auxdir=./build` makes sure all the build files are not polluting the top level. Could we keep that?

2023-03-27 15:33 UTC, kierun commented on Makefile
> +	$(FIND) indent -name "*.bak*" -maxdepth 1 -delete
Could you replace `"*.bak*" ` with "*.bak[0-9]" as it make it less greed?

2023-03-27 19:55 UTC, stevecooperorg commented on Makefile
> +	$(LATEXMK) -xelatex -interaction=nonstopmode $(PREVIEW) $*
I added this to .latexmkrc as 

```
$aux_dir = 'build';
```

I'm finding that the rc file's quite neat, especially as you add more documents and targets, to give consistent builds.

2023-03-27 20:04 UTC, closed without merging